** Sauce connect timeout to 3 minutes

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,9 +19,16 @@ before_install:
     if [ $TRAVIS_PULL_REQUEST != false ]; then
       curl -sS https://saucelabs.com/downloads/sc-4.3.12-linux.tar.gz|tar -xzC /tmp/;
       /tmp/sc-4.3.12-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_NUMBER -f /tmp/sc-ready -r 10 --pidfile /tmp/sc.pid --vm-version dev-varnish --daemonize;
-      while [ ! -f /tmp/sc-ready ]; do
-        sleep .5;
-      done
+      t=0;
+      while [ ! -f /tmp/sc-ready ]; do 
+        sleep 0.5; 
+        t=$((t+1)); 
+        if [ $t -gt 180 ]; then 
+          killall sc;
+          echo "Unable to get Sauce connection within 3 minutes";
+          exit 1;
+        fi;
+      done;
     fi;
   fi;
 install:
